const CHICAGO = "Chicago Buls";
const name = "Daburys";
console.log(CHICAGO);
let currentStatus = "Belezinha pura";
currentStatus = "Não belezinha pura";
console.log(currentStatus);
console.log("Followers:" + "72");
const numberflower = "27";
console.log("Followerts" + numberflower);
const nomberflower = 7 + 6;
console.log(nomberflower);
const brabin = 3 * 5;
console.log(brabin);
const brabim = 15 / 3;
console.log(brabim);
console.log(brabim + 1);
const total = brabin + brabim;
console.log(total);
let allowcokies = !true;
console.log(!allowcokies);
const isMorning = true;
const isEverning = !isMorning;
console.log(isEverning);
const lvlPlayer = 41;
console.log(lvlPlayer === 42);
console.log(lvlPlayer !== 42);
console.log(1 > 5);
console.log(4 >= 3);
